#!/bin/bash
set -e
cd PyML-0.7.14 && python setup.py build && python setup.py install && cd ..


python -m nltk.downloader punkt
python -m nltk.downloader wordnet
python -m nltk.downloader brown
python -m nltk.downloader conll2000
python -m nltk.downloader conll2002
python -m nltk.downloader treebank

python sentiment.py "This is a test sentence to get the juices flowing."

gunicorn server:app